[features]
seeds = false
[programs.localnet]
upzealo = "upzV36ZPSMavyifQCHf2jnNAPkCpZcq7MXbH6nxAa7h"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "wallets/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
